name: learn-github-actions-part-1
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g bats
      - run: bats -v
  check-git-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install git
      - run: git --version
  check-httpd-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install apache2
      - run: sudo ufw show app list
      - run: sudo ufw allow 'Apache'
      - run: sudo ufw status
      - run: sudo systemctl status apache2.service

