name: learn-github-actions-part-1
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g bats
      - run: bats -v
  check-git-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install git
      - run: git --version
  check-git-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install nginx
      - run: sudo ufw app list
      - run: sudo ufw allow 'Nginx HTTP'
      - run: sudo ufw status
      - run: sudo systemctl status nginx

